# Generated by Django 4.1.5 on 2023-01-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter book's natural language (e.g. English, French, German, etc.)", max_length=100),
        ),
    ]
